version: '3.9'

services:
  backend:
    build: 
      context: ./back
      dockerfile: ./build/Dockerfile
      target: local
    container_name: backend
    ports:
      - "8000:8000"
      - "3001:3001"
    volumes:
      - './back:/app'
