version: '3.9'

services:
  backend:
    build: 
      context: ./back
      dockerfile: ./build/Dockerfile
      target: dev
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - './back:/app'
  frontend:
    build:
      context: ./front
    container_name: frontend
    ports:
      - "3000:80"
